development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: elmerastudillo
  password: elmo123

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: elmerastudillo
  password: elmo123


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: postgres
  password: postgres
